### ISSUE TITLE
实验失败了

### ISSUE THREAD

**Issue by ilaipi** [libook/WSL-GUI#1]
我自己启动xlanch  在里面执行命令，是可以的，但是双击你的config.xlanch，图标出来就又消失了。我的xlanch配置：

我这都是用的默认参数，就改了一个   `Disable Access Control`，把这个改成了true，其它的都没改：
```
<?xml version="1.0" encoding="UTF-8"?>
<XLaunch WindowMode="MultiWindow" ClientMode="NoClient" LocalClient="False" Display="-1" LocalProgram="xcalc" RemoteProgram="xterm" RemotePassword="" PrivateKey="" RemoteHost="" RemoteUser="" XDMCPHost="" XDMCPBroadcast="False" XDMCPIndirect="False" Clipboard="True" ClipboardPrimary="True" ExtraParams="" Wgl="True" DisableAC="True" XDMCPTerminate="False"/>

```

还有就是我用这个启动的话，双击你的`wsl.ink`也是闪一下就没了。我看这个文件指向的是我系统的`powershell`吗？

没玩过这个，希望能学习一下

**Comment by libook** [comment]
抱歉之前没看到你的issues。

config.xlanch双击不会有任何视觉效果是正常的，因为大多XServer on Windows都是启动后静静地在系统托盘有个图标。

wsl.ink是个快捷方式，是使用PowerShell进入WSL环境再使用Windows上的XServer作为服务器启动Terminator终端模拟器，这个是被特意设计成隐藏执行的，所以看不到PowerShell界面是正常的，但是如果没出Terminator的界面的话就说明有问题，你可以自己手动打开PowerShell，然后执行bash进入WSL，再手动运行`/root/start_terminator`看看有什么输出。

**Comment by ilaipi** [comment]
我现在是不需要terminator了，用Windows Terminal直接做终端，效果特别好。用wsl里的vim，一点都不卡，甚至特别的流畅

反而我装了个wsl里面的git客户端，通过这个方式在win显示出来，卡是不卡，但是渲染效果不太好，并且输入法也有问题。所以还是放弃用wsl里面的软件，只用vim，tmux这些，非常完美。唯一的问题是现在解决不了代码的eol问题

**Comment by libook** [comment]
我用Terminator有两个原因：
1. 是我个人习惯用的终端模拟器，你可以对我提供的脚本稍加修改，换成任何你习惯用的GUI终端模拟器，如gnome-terminal、Guake（未测试过）。
2. 如果用Windows自己的Shell直接使用WSL命令行环境的话，执行任何GUI程序都要确保有DISPLAY环境变量，否者GUI程序找不到XServer，当然你可以把这个环境变量写到你的.bashrc或者.zshrc里，但如果WSL系统配置有些问题可能会遇到无法正常进入命令行Shell的情况。为了保险，我就没有把这个环境变量写入到.bashrc或.zshrc里，而是通过每次进入WSL执行start脚本来装载这个环境变量，而且一旦成功显示WSL下的GUI终端模拟器界面，你在这个终端模拟器里执行任何GUI程序都是在这个DISPLAY环境变量下执行的，无需额外配置。当然你可以根据自己的需求改成自己喜欢的方式来使用。

很多编辑器或IDE都支持配置EOL，这个你可以自己在网上搜一搜。

我是在WSL下用IDEA，显示效果完全OK，这是个基于Java的IDE，所以不用管主题的问题，如果是基于GTK的应用程序如Gnome桌面常用的那些程序，其显示样式可能会受到当前GTK主题的影响，换个主题可能会好很多。
另外也要注意是否有安装了好看的中文字体，你可以把Windows的字体从`系统盘:\Windows\Fonts`里复制到WSL里进行安装，也可以自己安装开源字体如文泉驿。

我目前基本上是纯英文开发，所以没大留意输入法的问题，有人是通过在WSL下再装一个Fcitx输入法来解决的，你可以找找相应的教程。
